// MODULE top, AUTOMATICALLY GENERATED BY PYTHON

/**/
`default_nettype wire


module top (
  // adc_4x16g_asnt: adc_16g_asnt
    input [0:0] adc4x16g_miso,
    input [3:0] gty0rxn_in,
    input [3:0] gty0rxp_in,
    input refclk0_n,
    input refclk0_p,
    output [3:0] adc4x16g_asnt_ctrl_0,
    output [0:0] adc4x16g_mosi,
    output [0:0] adc4x16g_sck,
    output [3:0] adc4x16g_sselb,
  // gpio: gpio
    output [0:0] adc_snapshot_inside_gpio_ext,
  // microblaze: xps:microblaze0
    input UART_rxd,
    output UART_txd,
  // onegbe: one_gbe
    input adc_snapshot_inside_one_gbe_dummy_port_in,
    input adc_snapshot_inside_one_gbe_refclk625_n,
    input adc_snapshot_inside_one_gbe_refclk625_p,
    input adc_snapshot_inside_one_gbe_rx_n,
    input adc_snapshot_inside_one_gbe_rx_p,
    inout phy_mdio,
    output adc_snapshot_inside_one_gbe_tx_n,
    output adc_snapshot_inside_one_gbe_tx_p,
    output phy_mdc,
    output phy_pdown_n,
  // vcu128: VCU128
    input sys_clk_n,
    input sys_clk_p
  );



  // usermodule: adc_snapshot_inside
  localparam ADC4X16G_WB_RAM0_WBID0 = 1;
  localparam ADC_SNAPSHOT_INSIDE_ONE_GBE_WBID0 = 2;
  localparam ADC_SNAPSHOT_INSIDE_REG_CNTRL_WBID0 = 3;
  localparam N_WB_SLAVES = 5;
  localparam SLAVE_ADDR = {
    32'h00021104, // sys_block
    32'h00021100, // reg_cntrl
    32'h00011100, // one_gbe
    32'h00010100, // adc4x16g_wb_ram0
    32'h00010000 // adc4x16g_controller0
    };
  localparam SLAVE_HIGH = {
    32'h00021123, // sys_block
    32'h00021103, // reg_cntrl
    32'h000210ff, // one_gbe
    32'h000110ff, // adc4x16g_wb_ram0
    32'h000100ff // adc4x16g_controller0
    };
  localparam SYS_BLOCK_INST_WBID0 = 4;
  localparam WB_ADC4X16G_CONTROLLER0_WBID0 = 0;

/*
  _____ _                   _     
 / ____(_)                 | |    
| (___  _  __ _ _ __   __ _| |___ 
 \___ \| |/ _` | '_ \ / _` | / __|
 ____) | | (_| | | | | (_| | \__ \ 
|_____/|_|\__, |_| |_|\__,_|_|___/
          __/ |                  
         |___/                   
*/
  // adc_4x16g_asnt: adc_16g_asnt
  wire [255:0] adc4x16g_data_out0;
  wire [15:0] adc4x16g_drp_data0;
  wire [15:0] adc4x16g_drp_data1;
  wire [15:0] adc4x16g_drp_data2;
  wire [15:0] adc4x16g_drp_data3;
  wire adc4x16g_empty0;
  wire adc4x16g_full0;
  wire adc4x16g_rxprbslocked0;
  wire adc4x16g_rxprbslocked1;
  wire adc4x16g_rxprbslocked2;
  wire adc4x16g_rxprbslocked3;
  wire [5:0] adc4x16g_snap_addr0;
  wire adc4x16g_snap_we0;
  wire adc_clk;
  wire adc_clk180;
  wire adc_clk270;
  wire adc_clk90;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a0;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a1;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a10;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a11;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a12;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a13;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a14;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a15;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a16;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a17;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a18;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a19;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a2;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a20;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a21;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a22;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a23;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a24;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a25;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a26;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a27;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a28;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a29;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a3;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a30;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a31;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a32;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a33;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a34;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a35;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a36;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a37;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a38;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a39;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a4;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a40;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a41;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a42;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a43;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a44;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a45;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a46;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a47;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a48;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a49;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a5;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a50;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a51;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a52;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a53;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a54;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a55;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a56;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a57;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a58;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a59;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a6;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a60;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a61;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a62;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a63;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a7;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a8;
  wire [3:0] adc_snapshot_inside_adc_16g_asnt_data_a9;
  wire adc_snapshot_inside_adc_16g_asnt_sync;
  wire mb_clk;
  wire rxslide0;
  wire rxslide1;
  wire rxslide2;
  wire rxslide3;
  wire sys_rst;
  // gpio: gpio
  wire [0:0] adc_snapshot_inside_gpio_gateway;
  // microblaze: xps:microblaze0
  wire [31:0] adc4x16g_config;
  wire [31:0] adc4x16g_drp_config;
  wire [31:0] adc4x16g_drp_data;
  wire [31:0] adc4x16g_match_pattern;
  wire adc4x16g_miso;
  wire adc4x16g_mosi;
  wire adc4x16g_sck;
  wire [3:0] adc4x16g_sselb;
  wire mb_intr;
  wire [3:0] mb_intr_v;
  wire wb_clk_i;
  wire wb_rst_i;
  wire wbm_ack_i;
  wire [31:0] wbm_adr_o;
  wire wbm_cyc_o;
  wire [31:0] wbm_dat_i;
  wire [31:0] wbm_dat_o;
  wire wbm_rst_o;
  wire [3:0] wbm_sel_o;
  wire wbm_stb_o;
  wire wbm_we_o;
  // onegbe: one_gbe
  wire [31:0] adc_snapshot_inside_one_gbe_app_dbg_data;
  wire adc_snapshot_inside_one_gbe_app_dbg_dvld;
  wire adc_snapshot_inside_one_gbe_app_rx_ack;
  wire adc_snapshot_inside_one_gbe_app_rx_badframe;
  wire [7:0] adc_snapshot_inside_one_gbe_app_rx_data;
  wire adc_snapshot_inside_one_gbe_app_rx_dvld;
  wire adc_snapshot_inside_one_gbe_app_rx_eof;
  wire adc_snapshot_inside_one_gbe_app_rx_overrun;
  wire adc_snapshot_inside_one_gbe_app_rx_rst;
  wire [31:0] adc_snapshot_inside_one_gbe_app_rx_srcip;
  wire [15:0] adc_snapshot_inside_one_gbe_app_rx_srcport;
  wire adc_snapshot_inside_one_gbe_app_tx_afull;
  wire [7:0] adc_snapshot_inside_one_gbe_app_tx_data;
  wire [31:0] adc_snapshot_inside_one_gbe_app_tx_destip;
  wire [15:0] adc_snapshot_inside_one_gbe_app_tx_destport;
  wire adc_snapshot_inside_one_gbe_app_tx_dvld;
  wire adc_snapshot_inside_one_gbe_app_tx_eof;
  wire adc_snapshot_inside_one_gbe_app_tx_overflow;
  wire adc_snapshot_inside_one_gbe_app_tx_rst;
  wire [7:0] adc_snapshot_inside_one_gbe_mac_gmii_rx_data;
  wire adc_snapshot_inside_one_gbe_mac_gmii_rx_dvld;
  wire adc_snapshot_inside_one_gbe_mac_gmii_rx_er;
  wire [7:0] adc_snapshot_inside_one_gbe_mac_gmii_tx_data;
  wire adc_snapshot_inside_one_gbe_mac_gmii_tx_en;
  wire adc_snapshot_inside_one_gbe_mac_gmii_tx_er;
  wire adc_snapshot_inside_one_gbe_mac_rx_badframe;
  wire [7:0] adc_snapshot_inside_one_gbe_mac_rx_data;
  wire adc_snapshot_inside_one_gbe_mac_rx_dvld;
  wire adc_snapshot_inside_one_gbe_mac_rx_goodframe;
  wire adc_snapshot_inside_one_gbe_mac_syncacquired;
  wire adc_snapshot_inside_one_gbe_mac_tx_ack;
  wire [7:0] adc_snapshot_inside_one_gbe_mac_tx_data;
  wire adc_snapshot_inside_one_gbe_mac_tx_dvld;
  wire gbe_userclk2_out;
  wire mdio_done;
  wire rst_125_out;
  wire sys_clk;
  wire sys_clk_rst_sync;
  // sw_reg: reg_cntrl
  wire [31:0] adc_snapshot_inside_reg_cntrl_user_data_out;
  // usermodule: adc_snapshot_inside
  wire wbm_err_i;
  wire [4:0] wbs_ack_i;
  wire [31:0] wbs_adr_o;
  wire [4:0] wbs_cyc_o;
  wire [159:0] wbs_dat_i;
  wire [31:0] wbs_dat_o;
  wire [4:0] wbs_err_i;
  wire [3:0] wbs_sel_o;
  wire [4:0] wbs_stb_o;
  wire wbs_we_o;
  // vcu128: VCU128
  wire clk_200;
  wire idelay_rdy;
  wire sys_clk180;
  wire sys_clk270;
  wire sys_clk90;
  // xsg: VCU128
  wire user_clk;
  wire user_clk180;
  wire user_clk270;
  wire user_clk90;

/*
  _____           _                            
 |_   _|         | |                           
   | |  _ __  ___| |_ __ _ _ __   ___ ___  ___ 
   | | | '_ \/ __| __/ _` | '_ \ / __/ _ \/ __|
  _| |_| | | \__ \ || (_| | | | | (_|  __/\__ \ 
 |_____|_| |_|___/\__\__,_|_| |_|\___\___||___/
*/
  // adc_4x16g_asnt: adc_16g_asnt
  adc4x16g_core #(
    .CHANNEL_SEL(0)
  ) adc4x16g_adc4x16g_inst0 (
    .XOR_ON(adc4x16g_config[24:24]),
    .adc_clk(adc_clk),
    .bit_sel(adc4x16g_config[19:18]),
    .clk100(user_clk),
    .clk_freerun(mb_clk),
    .data_out(adc4x16g_data_out0),
    .drp_addr(adc4x16g_drp_config[9:0]),
    .drp_data(adc4x16g_drp_data0),
    .drp_read(adc4x16g_drp_config[10]),
    .drp_reset(adc4x16g_drp_config[12:12]),
    .fifo_empty(adc4x16g_empty0),
    .fifo_full(adc4x16g_full0),
    .fifo_read(adc4x16g_config[25:25]),
    .fifo_reset(adc4x16g_config[17:17]),
    .gtwiz_reset_all_in(adc4x16g_config[16:16]),
    .gty0rxn_in(gty0rxn_in),
    .gty0rxp_in(gty0rxp_in),
    .match_pattern(adc4x16g_match_pattern),
    .pattern_match_enable(adc4x16g_config[27:27]),
    .prbs_error_count_reset(adc4x16g_drp_config[11:11]),
    .refclk0_n(refclk0_n),
    .refclk0_p(refclk0_p),
    .rxcdrhold(adc4x16g_config[22:22]),
    .rxprbserr_out(),
    .rxprbslocked(adc4x16g_rxprbslocked0),
    .rxslide(rxslide0),
    .write_interval(adc4x16g_drp_config[23:16])
  );


  ADC4X16G_Channel_Sel  adc4x16g_channel_sel (
    .channel_sel(adc4x16g_config[21:20]),
    .drp_data(adc4x16g_drp_data[15:0]),
    .drp_data0(adc4x16g_drp_data0),
    .drp_data1(adc4x16g_drp_data1),
    .drp_data2(adc4x16g_drp_data2),
    .drp_data3(adc4x16g_drp_data3),
    .rxprbslocked(adc4x16g_drp_data[16:16]),
    .rxprbslocked0(adc4x16g_rxprbslocked0),
    .rxprbslocked1(adc4x16g_rxprbslocked1),
    .rxprbslocked2(adc4x16g_rxprbslocked2),
    .rxprbslocked3(adc4x16g_rxprbslocked3),
    .rxslide(adc4x16g_config[23:23]),
    .rxslide0(rxslide0),
    .rxslide1(rxslide1),
    .rxslide2(rxslide2),
    .rxslide3(rxslide3)
  );


  wb_bram #(
    .LOG_USER_WIDTH(8),
    .N_REGISTERS(2),
    .USER_ADDR_BITS(6)
  ) adc4x16g_wb_ram0 (
    .user_addr(adc4x16g_snap_addr0),
    .user_clk(user_clk),
    .user_din(adc4x16g_data_out0),
    .user_dout(),
    .user_we(adc4x16g_snap_we0),
    .wb_ack_o(wbs_ack_i[ADC4X16G_WB_RAM0_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ADC4X16G_WB_RAM0_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ADC4X16G_WB_RAM0_WBID0+1)*32-1:(ADC4X16G_WB_RAM0_WBID0)*32]),
    .wb_err_o(wbs_err_i[ADC4X16G_WB_RAM0_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ADC4X16G_WB_RAM0_WBID0]),
    .wb_we_i(wbs_we_o)
  );


  data_splitter  data_splitter_inst0 (
    .data_in(adc4x16g_data_out0),
    .data_out0(adc_snapshot_inside_adc_16g_asnt_data_a0),
    .data_out1(adc_snapshot_inside_adc_16g_asnt_data_a1),
    .data_out10(adc_snapshot_inside_adc_16g_asnt_data_a10),
    .data_out11(adc_snapshot_inside_adc_16g_asnt_data_a11),
    .data_out12(adc_snapshot_inside_adc_16g_asnt_data_a12),
    .data_out13(adc_snapshot_inside_adc_16g_asnt_data_a13),
    .data_out14(adc_snapshot_inside_adc_16g_asnt_data_a14),
    .data_out15(adc_snapshot_inside_adc_16g_asnt_data_a15),
    .data_out16(adc_snapshot_inside_adc_16g_asnt_data_a16),
    .data_out17(adc_snapshot_inside_adc_16g_asnt_data_a17),
    .data_out18(adc_snapshot_inside_adc_16g_asnt_data_a18),
    .data_out19(adc_snapshot_inside_adc_16g_asnt_data_a19),
    .data_out2(adc_snapshot_inside_adc_16g_asnt_data_a2),
    .data_out20(adc_snapshot_inside_adc_16g_asnt_data_a20),
    .data_out21(adc_snapshot_inside_adc_16g_asnt_data_a21),
    .data_out22(adc_snapshot_inside_adc_16g_asnt_data_a22),
    .data_out23(adc_snapshot_inside_adc_16g_asnt_data_a23),
    .data_out24(adc_snapshot_inside_adc_16g_asnt_data_a24),
    .data_out25(adc_snapshot_inside_adc_16g_asnt_data_a25),
    .data_out26(adc_snapshot_inside_adc_16g_asnt_data_a26),
    .data_out27(adc_snapshot_inside_adc_16g_asnt_data_a27),
    .data_out28(adc_snapshot_inside_adc_16g_asnt_data_a28),
    .data_out29(adc_snapshot_inside_adc_16g_asnt_data_a29),
    .data_out3(adc_snapshot_inside_adc_16g_asnt_data_a3),
    .data_out30(adc_snapshot_inside_adc_16g_asnt_data_a30),
    .data_out31(adc_snapshot_inside_adc_16g_asnt_data_a31),
    .data_out32(adc_snapshot_inside_adc_16g_asnt_data_a32),
    .data_out33(adc_snapshot_inside_adc_16g_asnt_data_a33),
    .data_out34(adc_snapshot_inside_adc_16g_asnt_data_a34),
    .data_out35(adc_snapshot_inside_adc_16g_asnt_data_a35),
    .data_out36(adc_snapshot_inside_adc_16g_asnt_data_a36),
    .data_out37(adc_snapshot_inside_adc_16g_asnt_data_a37),
    .data_out38(adc_snapshot_inside_adc_16g_asnt_data_a38),
    .data_out39(adc_snapshot_inside_adc_16g_asnt_data_a39),
    .data_out4(adc_snapshot_inside_adc_16g_asnt_data_a4),
    .data_out40(adc_snapshot_inside_adc_16g_asnt_data_a40),
    .data_out41(adc_snapshot_inside_adc_16g_asnt_data_a41),
    .data_out42(adc_snapshot_inside_adc_16g_asnt_data_a42),
    .data_out43(adc_snapshot_inside_adc_16g_asnt_data_a43),
    .data_out44(adc_snapshot_inside_adc_16g_asnt_data_a44),
    .data_out45(adc_snapshot_inside_adc_16g_asnt_data_a45),
    .data_out46(adc_snapshot_inside_adc_16g_asnt_data_a46),
    .data_out47(adc_snapshot_inside_adc_16g_asnt_data_a47),
    .data_out48(adc_snapshot_inside_adc_16g_asnt_data_a48),
    .data_out49(adc_snapshot_inside_adc_16g_asnt_data_a49),
    .data_out5(adc_snapshot_inside_adc_16g_asnt_data_a5),
    .data_out50(adc_snapshot_inside_adc_16g_asnt_data_a50),
    .data_out51(adc_snapshot_inside_adc_16g_asnt_data_a51),
    .data_out52(adc_snapshot_inside_adc_16g_asnt_data_a52),
    .data_out53(adc_snapshot_inside_adc_16g_asnt_data_a53),
    .data_out54(adc_snapshot_inside_adc_16g_asnt_data_a54),
    .data_out55(adc_snapshot_inside_adc_16g_asnt_data_a55),
    .data_out56(adc_snapshot_inside_adc_16g_asnt_data_a56),
    .data_out57(adc_snapshot_inside_adc_16g_asnt_data_a57),
    .data_out58(adc_snapshot_inside_adc_16g_asnt_data_a58),
    .data_out59(adc_snapshot_inside_adc_16g_asnt_data_a59),
    .data_out6(adc_snapshot_inside_adc_16g_asnt_data_a6),
    .data_out60(adc_snapshot_inside_adc_16g_asnt_data_a60),
    .data_out61(adc_snapshot_inside_adc_16g_asnt_data_a61),
    .data_out62(adc_snapshot_inside_adc_16g_asnt_data_a62),
    .data_out63(adc_snapshot_inside_adc_16g_asnt_data_a63),
    .data_out7(adc_snapshot_inside_adc_16g_asnt_data_a7),
    .data_out8(adc_snapshot_inside_adc_16g_asnt_data_a8),
    .data_out9(adc_snapshot_inside_adc_16g_asnt_data_a9),
    .sync_in(~adc4x16g_empty0),
    .sync_out(adc_snapshot_inside_adc_16g_asnt_sync)
  );


  wb_adc4x16g_controller  wb_adc4x16g_controller0 (
    .rst(sys_rst),
    .snap_addr(adc4x16g_snap_addr0),
    .snap_we(adc4x16g_snap_we0),
    .user_clk(user_clk),
    .wb_ack_o(wbs_ack_i[WB_ADC4X16G_CONTROLLER0_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[WB_ADC4X16G_CONTROLLER0_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(WB_ADC4X16G_CONTROLLER0_WBID0+1)*32-1:(WB_ADC4X16G_CONTROLLER0_WBID0)*32]),
    .wb_err_o(wbs_err_i[WB_ADC4X16G_CONTROLLER0_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[WB_ADC4X16G_CONTROLLER0_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // gpio: gpio
  gpio_simulink2ext #(
    .CLK_PHASE(0),
    .DDR(0),
    .REG_IOB("true"),
    .WIDTH(1)
  ) adc_snapshot_inside_gpio (
    .clk(user_clk),
    .clk90(user_clk90),
    .gateway(adc_snapshot_inside_gpio_gateway),
    .io_pad(adc_snapshot_inside_gpio_ext)
  );

  // microblaze: xps:microblaze0
  adc_snapshot_inside  adc_snapshot_inside_inst (
    .adc_snapshot_inside_adc_16g_asnt_data_a0(adc_snapshot_inside_adc_16g_asnt_data_a0),
    .adc_snapshot_inside_adc_16g_asnt_data_a1(adc_snapshot_inside_adc_16g_asnt_data_a1),
    .adc_snapshot_inside_adc_16g_asnt_data_a10(adc_snapshot_inside_adc_16g_asnt_data_a10),
    .adc_snapshot_inside_adc_16g_asnt_data_a11(adc_snapshot_inside_adc_16g_asnt_data_a11),
    .adc_snapshot_inside_adc_16g_asnt_data_a12(adc_snapshot_inside_adc_16g_asnt_data_a12),
    .adc_snapshot_inside_adc_16g_asnt_data_a13(adc_snapshot_inside_adc_16g_asnt_data_a13),
    .adc_snapshot_inside_adc_16g_asnt_data_a14(adc_snapshot_inside_adc_16g_asnt_data_a14),
    .adc_snapshot_inside_adc_16g_asnt_data_a15(adc_snapshot_inside_adc_16g_asnt_data_a15),
    .adc_snapshot_inside_adc_16g_asnt_data_a16(adc_snapshot_inside_adc_16g_asnt_data_a16),
    .adc_snapshot_inside_adc_16g_asnt_data_a17(adc_snapshot_inside_adc_16g_asnt_data_a17),
    .adc_snapshot_inside_adc_16g_asnt_data_a18(adc_snapshot_inside_adc_16g_asnt_data_a18),
    .adc_snapshot_inside_adc_16g_asnt_data_a19(adc_snapshot_inside_adc_16g_asnt_data_a19),
    .adc_snapshot_inside_adc_16g_asnt_data_a2(adc_snapshot_inside_adc_16g_asnt_data_a2),
    .adc_snapshot_inside_adc_16g_asnt_data_a20(adc_snapshot_inside_adc_16g_asnt_data_a20),
    .adc_snapshot_inside_adc_16g_asnt_data_a21(adc_snapshot_inside_adc_16g_asnt_data_a21),
    .adc_snapshot_inside_adc_16g_asnt_data_a22(adc_snapshot_inside_adc_16g_asnt_data_a22),
    .adc_snapshot_inside_adc_16g_asnt_data_a23(adc_snapshot_inside_adc_16g_asnt_data_a23),
    .adc_snapshot_inside_adc_16g_asnt_data_a24(adc_snapshot_inside_adc_16g_asnt_data_a24),
    .adc_snapshot_inside_adc_16g_asnt_data_a25(adc_snapshot_inside_adc_16g_asnt_data_a25),
    .adc_snapshot_inside_adc_16g_asnt_data_a26(adc_snapshot_inside_adc_16g_asnt_data_a26),
    .adc_snapshot_inside_adc_16g_asnt_data_a27(adc_snapshot_inside_adc_16g_asnt_data_a27),
    .adc_snapshot_inside_adc_16g_asnt_data_a28(adc_snapshot_inside_adc_16g_asnt_data_a28),
    .adc_snapshot_inside_adc_16g_asnt_data_a29(adc_snapshot_inside_adc_16g_asnt_data_a29),
    .adc_snapshot_inside_adc_16g_asnt_data_a3(adc_snapshot_inside_adc_16g_asnt_data_a3),
    .adc_snapshot_inside_adc_16g_asnt_data_a30(adc_snapshot_inside_adc_16g_asnt_data_a30),
    .adc_snapshot_inside_adc_16g_asnt_data_a31(adc_snapshot_inside_adc_16g_asnt_data_a31),
    .adc_snapshot_inside_adc_16g_asnt_data_a32(adc_snapshot_inside_adc_16g_asnt_data_a32),
    .adc_snapshot_inside_adc_16g_asnt_data_a33(adc_snapshot_inside_adc_16g_asnt_data_a33),
    .adc_snapshot_inside_adc_16g_asnt_data_a34(adc_snapshot_inside_adc_16g_asnt_data_a34),
    .adc_snapshot_inside_adc_16g_asnt_data_a35(adc_snapshot_inside_adc_16g_asnt_data_a35),
    .adc_snapshot_inside_adc_16g_asnt_data_a36(adc_snapshot_inside_adc_16g_asnt_data_a36),
    .adc_snapshot_inside_adc_16g_asnt_data_a37(adc_snapshot_inside_adc_16g_asnt_data_a37),
    .adc_snapshot_inside_adc_16g_asnt_data_a38(adc_snapshot_inside_adc_16g_asnt_data_a38),
    .adc_snapshot_inside_adc_16g_asnt_data_a39(adc_snapshot_inside_adc_16g_asnt_data_a39),
    .adc_snapshot_inside_adc_16g_asnt_data_a4(adc_snapshot_inside_adc_16g_asnt_data_a4),
    .adc_snapshot_inside_adc_16g_asnt_data_a40(adc_snapshot_inside_adc_16g_asnt_data_a40),
    .adc_snapshot_inside_adc_16g_asnt_data_a41(adc_snapshot_inside_adc_16g_asnt_data_a41),
    .adc_snapshot_inside_adc_16g_asnt_data_a42(adc_snapshot_inside_adc_16g_asnt_data_a42),
    .adc_snapshot_inside_adc_16g_asnt_data_a43(adc_snapshot_inside_adc_16g_asnt_data_a43),
    .adc_snapshot_inside_adc_16g_asnt_data_a44(adc_snapshot_inside_adc_16g_asnt_data_a44),
    .adc_snapshot_inside_adc_16g_asnt_data_a45(adc_snapshot_inside_adc_16g_asnt_data_a45),
    .adc_snapshot_inside_adc_16g_asnt_data_a46(adc_snapshot_inside_adc_16g_asnt_data_a46),
    .adc_snapshot_inside_adc_16g_asnt_data_a47(adc_snapshot_inside_adc_16g_asnt_data_a47),
    .adc_snapshot_inside_adc_16g_asnt_data_a48(adc_snapshot_inside_adc_16g_asnt_data_a48),
    .adc_snapshot_inside_adc_16g_asnt_data_a49(adc_snapshot_inside_adc_16g_asnt_data_a49),
    .adc_snapshot_inside_adc_16g_asnt_data_a5(adc_snapshot_inside_adc_16g_asnt_data_a5),
    .adc_snapshot_inside_adc_16g_asnt_data_a50(adc_snapshot_inside_adc_16g_asnt_data_a50),
    .adc_snapshot_inside_adc_16g_asnt_data_a51(adc_snapshot_inside_adc_16g_asnt_data_a51),
    .adc_snapshot_inside_adc_16g_asnt_data_a52(adc_snapshot_inside_adc_16g_asnt_data_a52),
    .adc_snapshot_inside_adc_16g_asnt_data_a53(adc_snapshot_inside_adc_16g_asnt_data_a53),
    .adc_snapshot_inside_adc_16g_asnt_data_a54(adc_snapshot_inside_adc_16g_asnt_data_a54),
    .adc_snapshot_inside_adc_16g_asnt_data_a55(adc_snapshot_inside_adc_16g_asnt_data_a55),
    .adc_snapshot_inside_adc_16g_asnt_data_a56(adc_snapshot_inside_adc_16g_asnt_data_a56),
    .adc_snapshot_inside_adc_16g_asnt_data_a57(adc_snapshot_inside_adc_16g_asnt_data_a57),
    .adc_snapshot_inside_adc_16g_asnt_data_a58(adc_snapshot_inside_adc_16g_asnt_data_a58),
    .adc_snapshot_inside_adc_16g_asnt_data_a59(adc_snapshot_inside_adc_16g_asnt_data_a59),
    .adc_snapshot_inside_adc_16g_asnt_data_a6(adc_snapshot_inside_adc_16g_asnt_data_a6),
    .adc_snapshot_inside_adc_16g_asnt_data_a60(adc_snapshot_inside_adc_16g_asnt_data_a60),
    .adc_snapshot_inside_adc_16g_asnt_data_a61(adc_snapshot_inside_adc_16g_asnt_data_a61),
    .adc_snapshot_inside_adc_16g_asnt_data_a62(adc_snapshot_inside_adc_16g_asnt_data_a62),
    .adc_snapshot_inside_adc_16g_asnt_data_a63(adc_snapshot_inside_adc_16g_asnt_data_a63),
    .adc_snapshot_inside_adc_16g_asnt_data_a7(adc_snapshot_inside_adc_16g_asnt_data_a7),
    .adc_snapshot_inside_adc_16g_asnt_data_a8(adc_snapshot_inside_adc_16g_asnt_data_a8),
    .adc_snapshot_inside_adc_16g_asnt_data_a9(adc_snapshot_inside_adc_16g_asnt_data_a9),
    .adc_snapshot_inside_adc_16g_asnt_sync(adc_snapshot_inside_adc_16g_asnt_sync),
    .adc_snapshot_inside_gpio_gateway(adc_snapshot_inside_gpio_gateway),
    .adc_snapshot_inside_one_gbe_app_dbg_data(adc_snapshot_inside_one_gbe_app_dbg_data),
    .adc_snapshot_inside_one_gbe_app_dbg_dvld(adc_snapshot_inside_one_gbe_app_dbg_dvld),
    .adc_snapshot_inside_one_gbe_app_rx_ack(adc_snapshot_inside_one_gbe_app_rx_ack),
    .adc_snapshot_inside_one_gbe_app_rx_badframe(adc_snapshot_inside_one_gbe_app_rx_badframe),
    .adc_snapshot_inside_one_gbe_app_rx_data(adc_snapshot_inside_one_gbe_app_rx_data),
    .adc_snapshot_inside_one_gbe_app_rx_dvld(adc_snapshot_inside_one_gbe_app_rx_dvld),
    .adc_snapshot_inside_one_gbe_app_rx_eof(adc_snapshot_inside_one_gbe_app_rx_eof),
    .adc_snapshot_inside_one_gbe_app_rx_overrun(adc_snapshot_inside_one_gbe_app_rx_overrun),
    .adc_snapshot_inside_one_gbe_app_rx_rst(adc_snapshot_inside_one_gbe_app_rx_rst),
    .adc_snapshot_inside_one_gbe_app_rx_srcip(adc_snapshot_inside_one_gbe_app_rx_srcip),
    .adc_snapshot_inside_one_gbe_app_rx_srcport(adc_snapshot_inside_one_gbe_app_rx_srcport),
    .adc_snapshot_inside_one_gbe_app_tx_afull(adc_snapshot_inside_one_gbe_app_tx_afull),
    .adc_snapshot_inside_one_gbe_app_tx_data(adc_snapshot_inside_one_gbe_app_tx_data),
    .adc_snapshot_inside_one_gbe_app_tx_destip(adc_snapshot_inside_one_gbe_app_tx_destip),
    .adc_snapshot_inside_one_gbe_app_tx_destport(adc_snapshot_inside_one_gbe_app_tx_destport),
    .adc_snapshot_inside_one_gbe_app_tx_dvld(adc_snapshot_inside_one_gbe_app_tx_dvld),
    .adc_snapshot_inside_one_gbe_app_tx_eof(adc_snapshot_inside_one_gbe_app_tx_eof),
    .adc_snapshot_inside_one_gbe_app_tx_overflow(adc_snapshot_inside_one_gbe_app_tx_overflow),
    .adc_snapshot_inside_one_gbe_app_tx_rst(adc_snapshot_inside_one_gbe_app_tx_rst),
    .adc_snapshot_inside_reg_cntrl_user_data_out(adc_snapshot_inside_reg_cntrl_user_data_out),
    .clk(user_clk)
  );


  // xps:microblaze0: Microblaze Control and Monitoring subsystem
  cont_microblaze  cont_microblaze_inst (
    .ACK_I(wbm_ack_i),
    .ADC4X16G_CONFIG_tri_o(adc4x16g_config),
    .ADC4X16G_DRP_CONFIG_tri_o(adc4x16g_drp_config),
    .ADC4X16G_DRP_DATA_tri_i(adc4x16g_drp_data),
    .ADC4X16G_MATCH_PATTERN_tri_o(adc4x16g_match_pattern),
    .ADR_O(wbm_adr_o),
    .CYC_O(wbm_cyc_o),
    .Clk(wb_clk_i),
    .DAT_I(wbm_dat_i),
    .DAT_O(wbm_dat_o),
    .MISO(adc4x16g_miso),
    .MOSI(adc4x16g_mosi),
    .RST_O(wbm_rst_o),
    .Reset(wb_rst_i),
    .SCK(adc4x16g_sck),
    .SEL_O(wbm_sel_o),
    .SSELb(adc4x16g_sselb),
    .STB_O(wbm_stb_o),
    .UART_rxd(UART_rxd),
    .UART_txd(UART_txd),
    .WE_O(wbm_we_o),
    .dcm_locked(1'b1),
    .ext_intr(mb_intr)
  );

  // onegbe: one_gbe
  gbe_udp #(
    .CPU_PROMISCUOUS(1),
    .DIS_CPU_RX(0),
    .DIS_CPU_TX(0),
    .LOCAL_ENABLE(1),
    .LOCAL_GATEWAY(32'd1),
    .LOCAL_IP(32'd3232246026),
    .LOCAL_MAC(48'd20015998343868),
    .LOCAL_PORT(16'd4321)
  ) adc_snapshot_inside_one_gbe (
    .app_clk(user_clk),
    .app_dbg_data(adc_snapshot_inside_one_gbe_app_dbg_data),
    .app_dbg_dvld(adc_snapshot_inside_one_gbe_app_dbg_dvld),
    .app_rx_ack(adc_snapshot_inside_one_gbe_app_rx_ack),
    .app_rx_badframe(adc_snapshot_inside_one_gbe_app_rx_badframe),
    .app_rx_data(adc_snapshot_inside_one_gbe_app_rx_data),
    .app_rx_dvld(adc_snapshot_inside_one_gbe_app_rx_dvld),
    .app_rx_eof(adc_snapshot_inside_one_gbe_app_rx_eof),
    .app_rx_overrun(adc_snapshot_inside_one_gbe_app_rx_overrun),
    .app_rx_rst(adc_snapshot_inside_one_gbe_app_rx_rst),
    .app_rx_srcip(adc_snapshot_inside_one_gbe_app_rx_srcip),
    .app_rx_srcport(adc_snapshot_inside_one_gbe_app_rx_srcport),
    .app_tx_afull(adc_snapshot_inside_one_gbe_app_tx_afull),
    .app_tx_data(adc_snapshot_inside_one_gbe_app_tx_data),
    .app_tx_destip(adc_snapshot_inside_one_gbe_app_tx_destip),
    .app_tx_destport(adc_snapshot_inside_one_gbe_app_tx_destport),
    .app_tx_dvld(adc_snapshot_inside_one_gbe_app_tx_dvld),
    .app_tx_eof(adc_snapshot_inside_one_gbe_app_tx_eof),
    .app_tx_overflow(adc_snapshot_inside_one_gbe_app_tx_overflow),
    .app_tx_rst(adc_snapshot_inside_one_gbe_app_tx_rst),
    .mac_rx_badframe(adc_snapshot_inside_one_gbe_mac_rx_badframe),
    .mac_rx_clk(gbe_userclk2_out),
    .mac_rx_data(adc_snapshot_inside_one_gbe_mac_rx_data),
    .mac_rx_dvld(adc_snapshot_inside_one_gbe_mac_rx_dvld),
    .mac_rx_goodframe(adc_snapshot_inside_one_gbe_mac_rx_goodframe),
    .mac_rx_rst(rst_125_out),
    .mac_syncacquired(adc_snapshot_inside_one_gbe_mac_syncacquired),
    .mac_tx_ack(adc_snapshot_inside_one_gbe_mac_tx_ack),
    .mac_tx_clk(gbe_userclk2_out),
    .mac_tx_data(adc_snapshot_inside_one_gbe_mac_tx_data),
    .mac_tx_dvld(adc_snapshot_inside_one_gbe_mac_tx_dvld),
    .mac_tx_rst(rst_125_out),
    .wb_ack_o(wbs_ack_i[ADC_SNAPSHOT_INSIDE_ONE_GBE_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ADC_SNAPSHOT_INSIDE_ONE_GBE_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ADC_SNAPSHOT_INSIDE_ONE_GBE_WBID0+1)*32-1:(ADC_SNAPSHOT_INSIDE_ONE_GBE_WBID0)*32]),
    .wb_err_o(wbs_err_i[ADC_SNAPSHOT_INSIDE_ONE_GBE_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ADC_SNAPSHOT_INSIDE_ONE_GBE_WBID0]),
    .wb_we_i(wbs_we_o)
  );


  gig_eth_mac #(
    .MAX_FRAME_SIZE_JUMBO(9022),
    .MAX_FRAME_SIZE_STANDARD(1522)
  ) adc_snapshot_inside_one_gbe_mac (
    .conf_rx_en(1),
    .conf_rx_jumbo_en(0),
    .conf_rx_no_chk_crc(0),
    .conf_tx_en(1),
    .conf_tx_jumbo_en(0),
    .conf_tx_no_gen_crc(0),
    .gmii_col(0),
    .gmii_crs(0),
    .gmii_rx_data(adc_snapshot_inside_one_gbe_mac_gmii_rx_data),
    .gmii_rx_dvld(adc_snapshot_inside_one_gbe_mac_gmii_rx_dvld),
    .gmii_rx_er(adc_snapshot_inside_one_gbe_mac_gmii_rx_er),
    .gmii_tx_data(adc_snapshot_inside_one_gbe_mac_gmii_tx_data),
    .gmii_tx_en(adc_snapshot_inside_one_gbe_mac_gmii_tx_en),
    .gmii_tx_er(adc_snapshot_inside_one_gbe_mac_gmii_tx_er),
    .mac_rx_badframe(adc_snapshot_inside_one_gbe_mac_rx_badframe),
    .mac_rx_data(adc_snapshot_inside_one_gbe_mac_rx_data),
    .mac_rx_dvld(adc_snapshot_inside_one_gbe_mac_rx_dvld),
    .mac_rx_goodframe(adc_snapshot_inside_one_gbe_mac_rx_goodframe),
    .mac_tx_ack(adc_snapshot_inside_one_gbe_mac_tx_ack),
    .mac_tx_data(adc_snapshot_inside_one_gbe_mac_tx_data),
    .mac_tx_dvld(adc_snapshot_inside_one_gbe_mac_tx_dvld),
    .mac_tx_underrun(0),
    .reset(rst_125_out),
    .rx_clk(gbe_userclk2_out),
    .tx_clk(gbe_userclk2_out)
  );


  mdio_config  adc_snapshot_inside_one_gbe_mdio_config_inst (
    .done(mdio_done),
    .mdc(phy_mdc),
    .mdio(phy_mdio),
    .sys_clk(sys_clk),
    .sys_clk_rst_sync(sys_clk_rst_sync)
  );


  gig_ethernet_pcs_pma_sgmii_lvds  adc_snapshot_inside_one_gbe_pcs_pma (
    .an_adv_config_vector_0(16'b1101100000000001),
    .an_interrupt_0(),
    .an_restart_config_0(1'b0),
    .clk125_out(gbe_userclk2_out),
    .clk312_out(),
    .configuration_vector_0(5'b10000),
    .dummy_port_in(adc_snapshot_inside_one_gbe_dummy_port_in),
    .gmii_isolate_0(),
    .gmii_rx_dv_0(adc_snapshot_inside_one_gbe_mac_gmii_rx_dvld),
    .gmii_rx_er_0(adc_snapshot_inside_one_gbe_mac_gmii_rx_er),
    .gmii_rxd_0(adc_snapshot_inside_one_gbe_mac_gmii_rx_data),
    .gmii_tx_en_0(adc_snapshot_inside_one_gbe_mac_gmii_tx_en),
    .gmii_tx_er_0(adc_snapshot_inside_one_gbe_mac_gmii_tx_er),
    .gmii_txd_0(adc_snapshot_inside_one_gbe_mac_gmii_tx_data),
    .refclk625_n(adc_snapshot_inside_one_gbe_refclk625_n),
    .refclk625_p(adc_snapshot_inside_one_gbe_refclk625_p),
    .reset(sys_rst | ~mdio_done),
    .riu_prsnt_1(1'b0),
    .riu_prsnt_2(1'b0),
    .riu_prsnt_3(1'b0),
    .riu_rddata_1(16'b0),
    .riu_rddata_2(16'b0),
    .riu_rddata_3(16'b0),
    .riu_valid_1(1'b0),
    .riu_valid_2(1'b0),
    .riu_valid_3(1'b0),
    .rst_125_out(rst_125_out),
    .rx_dly_rdy_1(1'b1),
    .rx_dly_rdy_2(1'b1),
    .rx_dly_rdy_3(1'b1),
    .rx_vtc_rdy_1(1'b1),
    .rx_vtc_rdy_2(1'b1),
    .rx_vtc_rdy_3(1'b1),
    .rxn_0(adc_snapshot_inside_one_gbe_rx_n),
    .rxp_0(adc_snapshot_inside_one_gbe_rx_p),
    .sgmii_clk_en_0(),
    .sgmii_clk_f_0(),
    .sgmii_clk_r_0(),
    .signal_detect_0(1'b1),
    .speed_is_100_0(1'b0),
    .speed_is_10_100_0(1'b0),
    .status_vector_0(),
    .tx_dly_rdy_1(1'b1),
    .tx_dly_rdy_2(1'b1),
    .tx_dly_rdy_3(1'b1),
    .tx_vtc_rdy_1(1'b1),
    .tx_vtc_rdy_2(1'b1),
    .tx_vtc_rdy_3(1'b1),
    .txn_0(adc_snapshot_inside_one_gbe_tx_n),
    .txp_0(adc_snapshot_inside_one_gbe_tx_p)
  );

  // sw_reg: reg_cntrl
  wb_register_ppc2simulink #(
    .INIT_VAL(32'h0)
  ) adc_snapshot_inside_reg_cntrl (
    .user_clk(user_clk),
    .user_data_out(adc_snapshot_inside_reg_cntrl_user_data_out),
    .wb_ack_o(wbs_ack_i[ADC_SNAPSHOT_INSIDE_REG_CNTRL_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[ADC_SNAPSHOT_INSIDE_REG_CNTRL_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(ADC_SNAPSHOT_INSIDE_REG_CNTRL_WBID0+1)*32-1:(ADC_SNAPSHOT_INSIDE_REG_CNTRL_WBID0)*32]),
    .wb_err_o(wbs_err_i[ADC_SNAPSHOT_INSIDE_REG_CNTRL_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[ADC_SNAPSHOT_INSIDE_REG_CNTRL_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // sys_block: xps:sys_block0
  sys_block #(
    .BOARD_ID(12),
    .REV_MAJ(12),
    .REV_MIN(0),
    .REV_RCS(32)
  ) sys_block_inst (
    .user_clk(user_clk),
    .wb_ack_o(wbs_ack_i[SYS_BLOCK_INST_WBID0]),
    .wb_adr_i(wbs_adr_o[(0+1)*32-1:(0)*32]),
    .wb_clk_i(wb_clk_i),
    .wb_cyc_i(wbs_cyc_o[SYS_BLOCK_INST_WBID0]),
    .wb_dat_i(wbs_dat_o),
    .wb_dat_o(wbs_dat_i[(SYS_BLOCK_INST_WBID0+1)*32-1:(SYS_BLOCK_INST_WBID0)*32]),
    .wb_err_o(wbs_err_i[SYS_BLOCK_INST_WBID0]),
    .wb_rst_i(wb_rst_i),
    .wb_sel_i(wbs_sel_o),
    .wb_stb_i(wbs_stb_o[SYS_BLOCK_INST_WBID0]),
    .wb_we_i(wbs_we_o)
  );

  // usermodule: adc_snapshot_inside
  wbs_arbiter #(
    .N_SLAVES(N_WB_SLAVES),
    .SLAVE_ADDR(SLAVE_ADDR),
    .SLAVE_HIGH(SLAVE_HIGH),
    .TIMEOUT(1024)
  ) wbs_arbiter_inst (
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wbm_ack_o(wbm_ack_i),
    .wbm_adr_i(wbm_adr_o),
    .wbm_cyc_i(wbm_cyc_o),
    .wbm_dat_i(wbm_dat_o),
    .wbm_dat_o(wbm_dat_i),
    .wbm_err_o(wbm_err_i),
    .wbm_sel_i(wbm_sel_o),
    .wbm_stb_i(wbm_stb_o),
    .wbm_we_i(wbm_we_o),
    .wbs_ack_i(wbs_ack_i),
    .wbs_adr_o(wbs_adr_o),
    .wbs_cyc_o(wbs_cyc_o),
    .wbs_dat_i(wbs_dat_i),
    .wbs_dat_o(wbs_dat_o),
    .wbs_err_i(wbs_err_i),
    .wbs_sel_o(wbs_sel_o),
    .wbs_stb_o(wbs_stb_o),
    .wbs_we_o(wbs_we_o)
  );

  // vcu128: VCU128
  vcu128_infrastructure  vcu128_infrastructure_inst (
    .clk_200(clk_200),
    .idelay_rdy(idelay_rdy),
    .mb_clk(mb_clk),
    .sys_clk0(sys_clk),
    .sys_clk180(sys_clk180),
    .sys_clk270(sys_clk270),
    .sys_clk_buf_n(sys_clk_n),
    .sys_clk_buf_p(sys_clk_p),
    .sys_clk_rst_sync(sys_clk_rst_sync),
    .sys_rst(sys_rst)
  );


/*
                   _                                  _       
     /\           (_)                                | |      
    /  \   ___ ___ _  __ _ _ __  _ __ ___   ___ _ __ | |_ ___ 
   / /\ \ / __/ __| |/ _` | '_ \| '_ ` _ \ / _ \ '_ \| __/ __|
  / ____ \\__ \__ \ | (_| | | | | | | | | |  __/ | | | |_\__ \ 
 /_/    \_\___/___/_|\__, |_| |_|_| |_| |_|\___|_| |_|\__|___/
                      __/ |                                   
                     |___/                                    
*/
  // adc_4x16g_asnt: adc_16g_asnt
  assign adc4x16g_asnt_ctrl_0 = adc4x16g_config[3:0];
  assign adc_clk180 = ~adc_clk;
  assign adc_clk270 = adc_clk;
  assign adc_clk90 = ~adc_clk270;
  // microblaze: xps:microblaze0
  assign mb_intr = |mb_intr_v;
  assign wb_clk_i = mb_clk;
  assign wb_rst_i = sys_rst;
  // onegbe: one_gbe
  assign phy_pdown_n = 1'b1;
  // vcu128: VCU128
  assign sys_clk90 = ~sys_clk270;
  // xsg: VCU128
  assign user_clk = adc_clk;
  assign user_clk180 = adc_clk180;
  assign user_clk270 = adc_clk270;
  assign user_clk90 = adc_clk90;


endmodule