set_property PACKAGE_PIN AN40 [get_ports refclk0_p]
set_property PACKAGE_PIN H19 [get_ports adc4x16g_asnt_ctrl_0[0]]
set_property PACKAGE_PIN K24 [get_ports adc4x16g_asnt_ctrl_0[1]]
set_property PACKAGE_PIN E27 [get_ports adc4x16g_asnt_ctrl_0[2]]
set_property PACKAGE_PIN B16 [get_ports adc4x16g_asnt_ctrl_0[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_0[0]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_0[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_0[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_0[3]]
set_property PACKAGE_PIN AU53 [get_ports gty0rxp_in[0]]
set_property PACKAGE_PIN AT51 [get_ports gty0rxp_in[1]]
set_property PACKAGE_PIN AR53 [get_ports gty0rxp_in[2]]
set_property PACKAGE_PIN AP51 [get_ports gty0rxp_in[3]]
set_property PACKAGE_PIN H17 [get_ports adc4x16g_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_mosi]
set_property PACKAGE_PIN B22 [get_ports adc4x16g_miso]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_miso]
set_property PACKAGE_PIN G16 [get_ports adc4x16g_sck]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sck]
set_property PACKAGE_PIN K21 [get_ports adc4x16g_sselb[0]]
set_property PACKAGE_PIN E22 [get_ports adc4x16g_sselb[1]]
set_property PACKAGE_PIN D22 [get_ports adc4x16g_sselb[2]]
set_property PACKAGE_PIN B23 [get_ports adc4x16g_sselb[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[0]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[3]]
set_property PACKAGE_PIN AJ40 [get_ports refclk3_p]
set_property PACKAGE_PIN A25 [get_ports adc4x16g_asnt_ctrl_3[0]]
set_property PACKAGE_PIN G27 [get_ports adc4x16g_asnt_ctrl_3[1]]
set_property PACKAGE_PIN E26 [get_ports adc4x16g_asnt_ctrl_3[2]]
set_property PACKAGE_PIN D26 [get_ports adc4x16g_asnt_ctrl_3[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_3[0]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_3[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_3[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_asnt_ctrl_3[3]]
set_property PACKAGE_PIN AL49 [get_ports gty3rxp_in[0]]
set_property PACKAGE_PIN AK51 [get_ports gty3rxp_in[1]]
set_property PACKAGE_PIN AJ53 [get_ports gty3rxp_in[2]]
set_property PACKAGE_PIN AH51 [get_ports gty3rxp_in[3]]
set_property PACKAGE_PIN H17 [get_ports adc4x16g_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_mosi]
set_property PACKAGE_PIN B22 [get_ports adc4x16g_miso]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_miso]
set_property PACKAGE_PIN G16 [get_ports adc4x16g_sck]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sck]
set_property PACKAGE_PIN K21 [get_ports adc4x16g_sselb[0]]
set_property PACKAGE_PIN E22 [get_ports adc4x16g_sselb[1]]
set_property PACKAGE_PIN D22 [get_ports adc4x16g_sselb[2]]
set_property PACKAGE_PIN B23 [get_ports adc4x16g_sselb[3]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[0]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[1]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[2]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_sselb[3]]
set_property PACKAGE_PIN BH24 [get_ports adc4x16g_two_adcs_gpio_ext[0]]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_two_adcs_gpio_ext[0]]
set_property PACKAGE_PIN BL23 [get_ports adc4x16g_two_adcs_one_gbe_dummy_port_in]
set_property IOSTANDARD LVCMOS18 [get_ports adc4x16g_two_adcs_one_gbe_dummy_port_in]
set_property PACKAGE_PIN BG22 [get_ports adc4x16g_two_adcs_one_gbe_tx_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc4x16g_two_adcs_one_gbe_tx_p]
set_property PACKAGE_PIN BH22 [get_ports adc4x16g_two_adcs_one_gbe_tx_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc4x16g_two_adcs_one_gbe_tx_n]
set_property PACKAGE_PIN BJ22 [get_ports adc4x16g_two_adcs_one_gbe_rx_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc4x16g_two_adcs_one_gbe_rx_p]
set_property PACKAGE_PIN BK21 [get_ports adc4x16g_two_adcs_one_gbe_rx_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc4x16g_two_adcs_one_gbe_rx_n]
set_property PACKAGE_PIN BF22 [get_ports phy_pdown_n]
set_property IOSTANDARD LVCMOS18 [get_ports phy_pdown_n]
set_property PACKAGE_PIN BG23 [get_ports phy_mdio]
set_property IOSTANDARD LVCMOS18 [get_ports phy_mdio]
set_property PACKAGE_PIN BN27 [get_ports phy_mdc]
set_property IOSTANDARD LVCMOS18 [get_ports phy_mdc]
set_property PACKAGE_PIN BH27 [get_ports adc4x16g_two_adcs_one_gbe_refclk625_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc4x16g_two_adcs_one_gbe_refclk625_p]
set_property PACKAGE_PIN BJ27 [get_ports adc4x16g_two_adcs_one_gbe_refclk625_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc4x16g_two_adcs_one_gbe_refclk625_n]
set_property PACKAGE_PIN F36 [get_ports sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_n]
set_property PACKAGE_PIN F35 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_p]
set_property PACKAGE_PIN BP26 [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports UART_rxd]
set_property PACKAGE_PIN BN26 [get_ports UART_txd]
set_property IOSTANDARD LVCMOS18 [get_ports UART_txd]
create_clock -period 2.000 -name adcclk0 -waveform {0.000 1.000} [get_ports {refclk0_p}]
create_clock -period 2.000 -name adcclk3 -waveform {0.000 1.000} [get_ports {refclk3_p}]
create_clock -period 10.000 -name sys_clk_p_CLK -waveform {0.000 5.000} [get_ports {sys_clk_p}]
set_max_delay 1.0 -to [get_ports {adc4x16g_two_adcs_gpio_ext[*]}]
set_min_delay 1.0 -to [get_ports {adc4x16g_two_adcs_gpio_ext[*]}]
set_false_path -to [get_ports {adc4x16g_two_adcs_gpio_ext[*]}]
set_false_path -from [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins adc4x16g_two_adcs_one_gbe_pcs_pma/inst/clock_reset_i/Clk_Rst_I_Plle3_Tx/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins adc4x16g_two_adcs_one_gbe_pcs_pma/inst/clock_reset_i/Clk_Rst_I_Plle3_Tx/CLKOUT1]] -to [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT4]] -to [get_clocks -of_objects [get_pins adc4x16g_two_adcs_one_gbe_pcs_pma/inst/clock_reset_i/Clk_Rst_I_Plle3_Tx/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins adc4x16g_two_adcs_one_gbe_pcs_pma/inst/clock_reset_i/Clk_Rst_I_Plle3_Tx/CLKOUT1]] -to [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT4]]
set_false_path -from [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT4]]
set_false_path -from [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT4]] -to [get_clocks -of_objects [get_pins vcu128_infrastructure_inst/MMCM_BASE_inst/CLKOUT1]]
set_clock_groups -name asyncclocks_eth0 -asynchronous -group [get_clocks -include_generated_clocks sys_clk_p_CLK] -group [get_clocks -include_generated_clocks adcclk0]
set_clock_groups -name asyncclocks_eth3 -asynchronous -group [get_clocks -include_generated_clocks sys_clk_p_CLK] -group [get_clocks -include_generated_clocks adcclk3]
set_property CONFIG_VOLTAGE 1.8 [current_design]
